### ISSUE TITLE
Paper 1.20.5 Unsupported Java Runtime

### ISSUE THREAD

**Issue by NontKrub** [josxha/minecraft-paper-docker#3]
Hi, Developer

I currently have some issues with your image on the latest version. I use Watchtower to auto-update my container as you said in the instruction. It seems to have a problem with the Java Runtime that is not been updated. Any way to solve this problem? Log is Provided below.

Thanks!

```
nont@nont-ezserver:~$ docker logs Paper-Friend
Downloading mojang_1.20.5.jar
Applying patches
Starting org.bukkit.craftbukkit.Main
Exception in thread "ServerMain" java.lang.UnsupportedClassVersionError: org/bukkit/craftbukkit/Main has been compiled by a more recent version of the Java Runtime  (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
        at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.base/java.net.URLClassLoader.defineClass(Unknown Source)
        at java.base/java.net.URLClassLoader$1.run(Unknown Source)
        at java.base/java.net.URLClassLoader$1.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.base/java.net.URLClassLoader.findClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:38)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by josxha** [comment]
Thanks for creating the issue @NontKrub. Builds for 1.20.5 and 1.20.6 are now fixed.
